# Generated by Django 5.0.6 on 2024-05-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_api', '0003_alter_ingredient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='all_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='recipe',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rated_by',
            field=models.IntegerField(default=0),
        ),
    ]
